[project]
name = "dockercluster"
version = "0.1.0"
description = "A CLI tool for a live view of your docker containers running on a remote server."
readme = "README.md"
requires-python = ">=3.10"
dependencies = []

[project.scripts]
ds = "dockercluster:live_status"
dockerstats = "dockercluster:live_status"
